source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SVWebViewController', :head
pod "AFNetworking", "~> 2.3"
pod 'CCBottomRefreshControl'
pod 'SVProgressHUD'
pod 'UICKeyChainStore'
#pod 'UXCam'
pod 'HTPressableButton'
pod 'SDWebImage'
pod 'REMenu', '~> 1.10'
pod 'EAIntroView'
pod 'SVPullToRefresh'
pod 'Mantle'
pod 'CardIO'
pod 'Stripe'
pod 'PaymentKit'
pod 'Lambda-Alert'
pod 'RESideMenu'
#pod 'Google-Mobile-Ads-SDK', '~> 6.10'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'GoogleAnalytics-iOS-SDK', '3.10'
pod 'Fabric/Crashlytics'
pod 'Parse', '~> 1.7.4'
pod 'pop', '~> 1.0'
pod 'POP+MCAnimate', '~> 1.0'